version: '3.8'
services:
  web:
    build: .
    container_name: sibora-web
    ports:
      - "5100:5100"
    environment:
      NEXT_TELEMETRY_DISABLED: '1'
      PORT: '5100'
    restart: unless-stopped

